/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HarkapAmbulanceWlList {
    }
}
declare global {
    interface HTMLHarkapAmbulanceWlListElement extends Components.HarkapAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLHarkapAmbulanceWlListElement: {
        prototype: HTMLHarkapAmbulanceWlListElement;
        new (): HTMLHarkapAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "harkap-ambulance-wl-list": HTMLHarkapAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface HarkapAmbulanceWlList {
    }
    interface IntrinsicElements {
        "harkap-ambulance-wl-list": HarkapAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "harkap-ambulance-wl-list": LocalJSX.HarkapAmbulanceWlList & JSXBase.HTMLAttributes<HTMLHarkapAmbulanceWlListElement>;
        }
    }
}
