/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HarkapAmbulanceLogEditor {
        "apiBase": string;
        "basePath": string;
        "entryId": string;
        "logId": string;
    }
    interface HarkapAmbulanceLogList {
        "apiBase": string;
        "deviceId": string;
    }
    interface HarkapAmbulanceWlApp {
        "apiBase": string;
        "basePath": string;
    }
    interface HarkapAmbulanceWlEditor {
        "apiBase": string;
        "basePath": string;
        "entryId": string;
    }
    interface HarkapAmbulanceWlList {
        "apiBase": string;
    }
}
export interface HarkapAmbulanceLogEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHarkapAmbulanceLogEditorElement;
}
export interface HarkapAmbulanceLogListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHarkapAmbulanceLogListElement;
}
export interface HarkapAmbulanceWlEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHarkapAmbulanceWlEditorElement;
}
export interface HarkapAmbulanceWlListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHarkapAmbulanceWlListElement;
}
declare global {
    interface HTMLHarkapAmbulanceLogEditorElementEventMap {
        "log-closed": string;
    }
    interface HTMLHarkapAmbulanceLogEditorElement extends Components.HarkapAmbulanceLogEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHarkapAmbulanceLogEditorElementEventMap>(type: K, listener: (this: HTMLHarkapAmbulanceLogEditorElement, ev: HarkapAmbulanceLogEditorCustomEvent<HTMLHarkapAmbulanceLogEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHarkapAmbulanceLogEditorElementEventMap>(type: K, listener: (this: HTMLHarkapAmbulanceLogEditorElement, ev: HarkapAmbulanceLogEditorCustomEvent<HTMLHarkapAmbulanceLogEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHarkapAmbulanceLogEditorElement: {
        prototype: HTMLHarkapAmbulanceLogEditorElement;
        new (): HTMLHarkapAmbulanceLogEditorElement;
    };
    interface HTMLHarkapAmbulanceLogListElementEventMap {
        "log-clicked": string;
    }
    interface HTMLHarkapAmbulanceLogListElement extends Components.HarkapAmbulanceLogList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHarkapAmbulanceLogListElementEventMap>(type: K, listener: (this: HTMLHarkapAmbulanceLogListElement, ev: HarkapAmbulanceLogListCustomEvent<HTMLHarkapAmbulanceLogListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHarkapAmbulanceLogListElementEventMap>(type: K, listener: (this: HTMLHarkapAmbulanceLogListElement, ev: HarkapAmbulanceLogListCustomEvent<HTMLHarkapAmbulanceLogListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHarkapAmbulanceLogListElement: {
        prototype: HTMLHarkapAmbulanceLogListElement;
        new (): HTMLHarkapAmbulanceLogListElement;
    };
    interface HTMLHarkapAmbulanceWlAppElement extends Components.HarkapAmbulanceWlApp, HTMLStencilElement {
    }
    var HTMLHarkapAmbulanceWlAppElement: {
        prototype: HTMLHarkapAmbulanceWlAppElement;
        new (): HTMLHarkapAmbulanceWlAppElement;
    };
    interface HTMLHarkapAmbulanceWlEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLHarkapAmbulanceWlEditorElement extends Components.HarkapAmbulanceWlEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHarkapAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLHarkapAmbulanceWlEditorElement, ev: HarkapAmbulanceWlEditorCustomEvent<HTMLHarkapAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHarkapAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLHarkapAmbulanceWlEditorElement, ev: HarkapAmbulanceWlEditorCustomEvent<HTMLHarkapAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHarkapAmbulanceWlEditorElement: {
        prototype: HTMLHarkapAmbulanceWlEditorElement;
        new (): HTMLHarkapAmbulanceWlEditorElement;
    };
    interface HTMLHarkapAmbulanceWlListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLHarkapAmbulanceWlListElement extends Components.HarkapAmbulanceWlList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHarkapAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLHarkapAmbulanceWlListElement, ev: HarkapAmbulanceWlListCustomEvent<HTMLHarkapAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHarkapAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLHarkapAmbulanceWlListElement, ev: HarkapAmbulanceWlListCustomEvent<HTMLHarkapAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHarkapAmbulanceWlListElement: {
        prototype: HTMLHarkapAmbulanceWlListElement;
        new (): HTMLHarkapAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "harkap-ambulance-log-editor": HTMLHarkapAmbulanceLogEditorElement;
        "harkap-ambulance-log-list": HTMLHarkapAmbulanceLogListElement;
        "harkap-ambulance-wl-app": HTMLHarkapAmbulanceWlAppElement;
        "harkap-ambulance-wl-editor": HTMLHarkapAmbulanceWlEditorElement;
        "harkap-ambulance-wl-list": HTMLHarkapAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface HarkapAmbulanceLogEditor {
        "apiBase"?: string;
        "basePath"?: string;
        "entryId"?: string;
        "logId"?: string;
        "onLog-closed"?: (event: HarkapAmbulanceLogEditorCustomEvent<string>) => void;
    }
    interface HarkapAmbulanceLogList {
        "apiBase"?: string;
        "deviceId"?: string;
        "onLog-clicked"?: (event: HarkapAmbulanceLogListCustomEvent<string>) => void;
    }
    interface HarkapAmbulanceWlApp {
        "apiBase"?: string;
        "basePath"?: string;
    }
    interface HarkapAmbulanceWlEditor {
        "apiBase"?: string;
        "basePath"?: string;
        "entryId"?: string;
        "onEditor-closed"?: (event: HarkapAmbulanceWlEditorCustomEvent<string>) => void;
    }
    interface HarkapAmbulanceWlList {
        "apiBase"?: string;
        "onEntry-clicked"?: (event: HarkapAmbulanceWlListCustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "harkap-ambulance-log-editor": HarkapAmbulanceLogEditor;
        "harkap-ambulance-log-list": HarkapAmbulanceLogList;
        "harkap-ambulance-wl-app": HarkapAmbulanceWlApp;
        "harkap-ambulance-wl-editor": HarkapAmbulanceWlEditor;
        "harkap-ambulance-wl-list": HarkapAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "harkap-ambulance-log-editor": LocalJSX.HarkapAmbulanceLogEditor & JSXBase.HTMLAttributes<HTMLHarkapAmbulanceLogEditorElement>;
            "harkap-ambulance-log-list": LocalJSX.HarkapAmbulanceLogList & JSXBase.HTMLAttributes<HTMLHarkapAmbulanceLogListElement>;
            "harkap-ambulance-wl-app": LocalJSX.HarkapAmbulanceWlApp & JSXBase.HTMLAttributes<HTMLHarkapAmbulanceWlAppElement>;
            "harkap-ambulance-wl-editor": LocalJSX.HarkapAmbulanceWlEditor & JSXBase.HTMLAttributes<HTMLHarkapAmbulanceWlEditorElement>;
            "harkap-ambulance-wl-list": LocalJSX.HarkapAmbulanceWlList & JSXBase.HTMLAttributes<HTMLHarkapAmbulanceWlListElement>;
        }
    }
}
